import { expect, test } from '@playwright/test'

test('dashboard navigation, preferences, and native-only settings', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'A fresh start for your finances.' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'A peaceful floating island with a purple-roofed home, trees, and a pond' })).toHaveJSProperty('complete', true)
  await page.screenshot({ path: 'test-results/home.png', fullPage: true })
  await expect(page.getByRole('button', { name: 'Expand sidebar' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Expand sidebar' })).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('header').getByRole('button')).toHaveCount(0)
  expect(await page.getByRole('complementary').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  const sidebarBefore = await page.getByRole('complementary').boundingBox()
  expect(sidebarBefore?.y).toBe(0)
  expect(sidebarBefore?.height).toBe(page.viewportSize()!.height)
  await page.locator('main').evaluate(element => { element.scrollTop = element.scrollHeight })
  expect(await page.getByRole('complementary').boundingBox()).toEqual(sidebarBefore)
  const nav = page.getByRole('navigation', { name: 'Main navigation' })
  await nav.getByRole('link', { name: 'Accounts', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A place for every account.' })).toBeVisible()
  await nav.getByRole('link', { name: 'Income', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Know what’s coming in.' })).toBeVisible()
  await nav.getByRole('link', { name: 'Settings', exact: true }).click()
  await expect(page.getByText('Open the desktop app to access your local settings.')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Make Heyday yours.' })).toBeVisible()
  await page.getByLabel('Theme', { exact: true }).selectOption('dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Expand sidebar' }).click()
  await expect(nav.getByRole('link', { name: 'Home', exact: true })).toContainText('Home')
  const handle = page.getByRole('separator', { name: 'Resize sidebar' })
  const edge = await handle.boundingBox()
  await page.mouse.move(edge!.x + edge!.width / 2, edge!.y + 150)
  await page.mouse.down()
  await page.mouse.move(edge!.x + edge!.width / 2 + 80, edge!.y + 150)
  await page.mouse.up()
  await expect(handle).toHaveAttribute('aria-valuenow', '264')
  await page.reload()
  await expect(handle).toHaveAttribute('aria-valuenow', '264')
  await handle.focus()
  await page.keyboard.press('ArrowRight')
  await expect(handle).toHaveAttribute('aria-valuenow', '274')
  await page.getByRole('button', { name: 'Collapse sidebar' }).click()
  expect((await page.getByRole('complementary').boundingBox())?.width).toBe(48)
  await page.getByRole('button', { name: 'Expand sidebar' }).click()
  expect((await page.getByRole('complementary').boundingBox())?.width).toBe(274)
  expect((await page.getByRole('complementary').boundingBox())?.height).toBe(page.viewportSize()!.height)
  expect(await page.getByRole('complementary').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(errors).toEqual([])
})
