import { test, expect } from '@playwright/test'
import type { NewTransaction, Transaction, SaveTransactionOption, TransactionOptions } from '../src/lib/desktop'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    const uiErrors: string[] = []
    Object.assign(window, { uiErrors })
    window.addEventListener('error', event => uiErrors.push(event.message))
    Object.defineProperty(window, 'isTauri', { value: true })
    Object.defineProperty(window, '__TAURI_INTERNALS__', { value: { invoke: async (command: string, args: { input: NewTransaction & SaveTransactionOption; id: string }) => {
      const rows = (): Transaction[] => JSON.parse(localStorage.getItem('transactions') ?? '[]')
      const accounts = [{ id: 'bank', name: 'Bank', type: 'bank', opening_balance: '10000', current_balance: '10000' }, { id: 'card', name: 'Card', type: 'credit_card', opening_balance: '5000', current_balance: '5000' }].map(account => ({ ...account, institution: null, last_four: null, notes: null, credit_limit: null, statement_day: null, payment_due_day: null, interest_rate_ten_thousandths: null, monthly_installment: null }))
      if (sessionStorage.getItem('loan-count') !== null) accounts.push({ ...accounts[0], id: 'loan', name: 'Home loan', type: 'loan', current_balance: '1000000' })
      const options = (): TransactionOptions => JSON.parse(localStorage.getItem('spending-options') ?? '{"payees":[],"categories":[]}')
      const enrichedRows = () => rows().map(row => ({ ...row, payee_name: options().payees.find(item => item.id === row.payee_id)?.name ?? null, category_name: options().categories.find(item => item.id === row.category_id)?.name ?? null }))
      switch (command) {
        case 'plugin:app|version': return '0.1.0'
        case 'get_settings': return { currency: sessionStorage.getItem('no-currency') ? null : 'THB', period_start_day: 1 }
        case 'list_accounts':
          if (sessionStorage.getItem('fail-accounts')) throw 'Load failed'
          if (sessionStorage.getItem('many-accounts')) return Array.from({ length: 40 }, (_, index) => ({ ...accounts[0], id: `bank-${index}`, name: `Bank ${String(index + 1).padStart(2, '0')}` }))
          return sessionStorage.getItem('no-accounts') ? [] : accounts.filter(a => !sessionStorage.getItem('hide-card') || a.id !== 'card')
        case 'get_financial_data': return { settings: { currency: 'THB', period_start_day: 1 }, accounts, transactions: enrichedRows(), incomes: [], plans: [], categories: options().categories }
        case 'list_incomes': return [{id:'salary',name:'Company salary',type:'salary',is_active:true,destination_account_id:'bank'}]
        case 'get_loan_account':
          if (sessionStorage.getItem('fail-loan-load')) throw 'Load failed'
          return { contracts: Array.from({ length: Number(sessionStorage.getItem('loan-count')) }, (_, n) => ({ id: `contract-${n}`, name: `Contract ${n + 1}`, needs_review: false })) }
        case 'record_loan_repayment':
          if (sessionStorage.getItem('fail')) throw 'Save failed. Try again.'
          localStorage.setItem('loan-payment', JSON.stringify(args.input)); return
        case 'list_transaction_options': return options()
        case 'save_transaction_option': {
          if (sessionStorage.getItem('hold-option')) await new Promise<void>(resolve => window.addEventListener('release-option', () => resolve(), { once: true }))
          if (sessionStorage.getItem('fail-option')) throw 'Could not save option.'
          const lists = options()
          const key = args.input.kind === 'payee' ? 'payees' : 'categories'
          const name = args.input.name.trim().replace(/\s+/g, ' ')
          if (lists[key].some(item => item.id !== args.input.id && item.name.toLowerCase() === name.toLowerCase())) throw 'That name already exists.'
          const value = { id: args.input.id ?? crypto.randomUUID(), name, icon: args.input.icon ?? lists[key].find(item => item.id === args.input.id)?.icon ?? 'tag', is_archived: args.input.is_archived }
          lists[key] = [...lists[key].filter(item => item.id !== value.id), value]
          localStorage.setItem('spending-options', JSON.stringify(lists))
          return value
        }
        case 'list_transactions': return enrichedRows()
        case 'create_transaction': {
          if (sessionStorage.getItem('hold-save')) await new Promise<void>(resolve => window.addEventListener('release-save', () => resolve(), { once: true }))
          if (sessionStorage.getItem('fail')) throw 'Save failed. Try again.'
          const row = { ...args.input, id: crypto.randomUUID(), account_name: accounts.find(a => a.id === args.input.account_id)!.name, destination_account_name: args.input.destination_account_id ? 'Card' : null }
          localStorage.setItem('transactions', JSON.stringify([row, ...rows()]))
          return row
        }
        case 'delete_transaction': localStorage.setItem('transactions', JSON.stringify(rows().filter(row => row.id !== args.id))); return
        default: throw new Error(command)
      }
    } } })
  })
})

for (const count of [0, 1, 2]) {
test(`quick loan repayment handles ${count} contracts and preserves failed drafts`, async ({ page }) => {
  await page.addInitScript(count => sessionStorage.setItem('loan-count', String(count)), count)
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Amount (THB)', { exact: true }).fill('5000')
  await page.getByLabel('Transaction type', { exact: true }).selectOption('repayment')
  await page.getByLabel('To account', { exact: true }).fill('Home loan')
  await page.getByLabel('To account', { exact: true }).press('Enter')
  await expect(page.getByLabel('Total payment (THB)', { exact: true })).toHaveValue('5000')
  await expect(page.getByRole('button', { name: 'Save transaction', exact: true })).toBeEnabled()
  if (count > 1) await page.getByLabel('Contract', { exact: true }).selectOption('contract-1')
  else await expect(page.getByRole('combobox', { name: 'Contract', exact: true })).toHaveCount(0)
  await page.getByLabel('Interest', { exact: true }).fill('800')
  await page.getByLabel('Fees', { exact: true }).fill('200')
  await expect(page.getByLabel('Principal', { exact: true })).toHaveValue('4,000.00 THB')
  await page.getByLabel('Description (optional)', { exact: true }).fill('Monthly loan')
  await page.getByLabel('Cleared in from account', { exact: true }).check()
  await page.evaluate(() => sessionStorage.setItem('fail', '1'))
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Save failed')
  await expect(page.getByLabel('Interest', { exact: true })).toHaveValue('800')
  await page.evaluate(() => sessionStorage.removeItem('fail'))
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('loan-payment')!))
  expect(saved).toMatchObject({ loan_account_id: 'loan', contract_id: count === 0 ? null : `contract-${count - 1}`, account_id: 'bank', total: '500000', principal: '400000', interest: '80000', fee: '20000', cleared: true, description: 'Monthly loan' })
  await expect(page.getByLabel('Interest', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Fees', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Total payment (THB)', { exact: true })).toBeFocused()
  await expect(page.getByLabel('To account', { exact: true })).toHaveValue('Home loan')
  await page.getByLabel('Total payment (THB)', { exact: true }).fill('100')
  await page.getByLabel('Interest', { exact: true }).fill('101')
  await expect(page.getByRole('alert')).toContainText('Interest and fees cannot exceed')
  await page.getByLabel('Interest', { exact: true }).fill('0')
  await page.getByLabel('Total payment (THB)', { exact: true }).press('Enter')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})
}

test('loan detail load errors block saving and retry preserves entered charges', async ({ page }) => {
  await page.addInitScript(() => { sessionStorage.setItem('loan-count', '0'); sessionStorage.setItem('fail-loan-load', '1') })
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Transaction type', { exact: true }).selectOption('repayment')
  await page.getByLabel('To account', { exact: true }).fill('Home loan')
  await page.getByLabel('To account', { exact: true }).press('Enter')
  await expect(page.getByRole('alert')).toContainText('Could not load loan details')
  await expect(page.getByRole('button', { name: 'Save transaction', exact: true })).toBeDisabled()
  await page.getByLabel('Total payment (THB)', { exact: true }).fill('5000')
  await page.getByLabel('Interest', { exact: true }).fill('800')
  await page.evaluate(() => sessionStorage.removeItem('fail-loan-load'))
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save transaction', exact: true })).toBeEnabled()
  await expect(page.getByLabel('Interest', { exact: true })).toHaveValue('800')
})

for (const viewport of [{ width: 1200, height: 800 }, { width: 480, height: 600 }]) {
test(`account dropdowns scroll with the wheel inside the transaction dialog at ${viewport.width}px`, async ({ page }) => {
  await page.setViewportSize(viewport)
  await page.addInitScript(() => sessionStorage.setItem('many-accounts', '1'))
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Amount (THB)', { exact: true }).fill('12.34')
  for (const field of ['Account', 'From account', 'To account']) {
    if (field === 'From account') await page.getByLabel('Transaction type', { exact: true }).selectOption('transfer')
    const input = page.getByRole('combobox', { name: field, exact: true })
    await input.click()
    const list = page.getByRole('listbox', { name: 'Accounts', exact: true })
    await expect(list).toBeVisible()
    await list.hover()
    await page.mouse.wheel(0, 250)
    await expect.poll(() => list.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
    await page.mouse.wheel(0, 3000)
    const last = list.getByRole('option', { name: 'Bank 40', exact: true })
    await expect(last).toBeInViewport()
    await last.click()
    await expect(input).toHaveValue('Bank 40')
    await expect(list).not.toBeVisible()
    // Leave the last account available as a destination on the next pass.
    if (field !== 'To account') {
      await input.fill('Bank 01')
      await input.press('Enter')
    }
  }
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toHaveValue('12.34')
})
}

test('record activity, retain failed forms, filter, and confirm deletion', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Description (optional)', { exact: true }).fill('Unsaved')
  await page.keyboard.press('Escape')
  await expect(page.getByText('Discard your unsaved transaction?')).toBeVisible()
  await page.getByRole('button', { name: 'Discard changes' }).click()
  for (const type of ['expense', 'income', 'transfer', 'repayment']) {
    await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
    await page.getByLabel('Transaction type', { exact: true }).selectOption(type)
    await page.getByLabel(type === 'income' || type === 'expense' ? 'Account' : 'From account', { exact: true }).fill('Bank'); await page.getByLabel(type === 'income' || type === 'expense' ? 'Account' : 'From account', { exact: true }).press('Enter')
    if (type === 'transfer' || type === 'repayment') {
      await page.getByLabel('To account', { exact: true }).fill('Card')
      await page.getByLabel('To account', { exact: true }).press('Enter')
    }
    await page.getByLabel('Amount (THB)', { exact: true }).fill('12.34')
    await page.getByLabel('Description (optional)', { exact: true }).fill(`Test ${type}`)
    if (type === 'expense') {
      await page.evaluate(() => sessionStorage.setItem('fail', '1'))
      await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
      await expect(page.getByRole('alert')).toContainText('Save failed')
      await page.evaluate(() => sessionStorage.removeItem('fail'))
    }
    await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(page.getByRole('rowheader', { name: `Test ${type}` })).toBeVisible()
  }
  await page.reload()
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(4)
  await page.getByLabel('Filter by account').selectOption('card')
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Delete Test repayment', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('rowheader', { name: 'Test repayment' })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Test repayment', exact: true }).click()
  await page.getByRole('button', { name: 'Delete transaction', exact: true }).click()
  await expect(page.getByRole('rowheader', { name: 'Test repayment' })).not.toBeVisible()
})

for (const [platform, shortcut] of [['MacIntel', 'Meta+n'], ['Win32', 'Control+n']]) {
  test(`${shortcut} and the header default a viewed loan to the repayment destination`, async ({ page }) => {
    await page.addInitScript(platform => {
      Object.defineProperty(navigator, 'platform', { value: platform })
      sessionStorage.setItem('loan-count', '0')
      localStorage.setItem('transaction-last-account', 'card')
    }, platform)
    await page.goto('/#/accounts/loan/details')
    await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
    await expect(page.getByLabel('Transaction type', { exact: true })).toHaveValue('repayment')
    await expect(page.getByLabel('From account', { exact: true })).toHaveValue('Bank')
    await expect(page.getByLabel('To account', { exact: true })).toHaveValue('Home loan')
    await expect(page.getByLabel('Total payment (THB)', { exact: true })).toBeEmpty()
    await expect(page.getByLabel('Interest', { exact: true })).toHaveValue('0')
    await expect(page.getByLabel('Fees', { exact: true })).toHaveValue('0')
    await page.keyboard.press('Escape')
    await page.keyboard.press(shortcut)
    await expect(page.getByLabel('Transaction type', { exact: true })).toHaveValue('repayment')
    await expect(page.getByLabel('To account', { exact: true })).toHaveValue('Home loan')
    await page.getByLabel('Transaction type', { exact: true }).selectOption('expense')
    await page.getByLabel('Amount (THB)', { exact: true }).fill('12')
    await page.keyboard.press(shortcut)
    await expect(page.getByLabel('Transaction type', { exact: true })).toHaveValue('expense')
    await expect(page.getByLabel('Amount (THB)', { exact: true })).toHaveValue('12')
  })

  test(`${shortcut} and the header use the viewed account without resetting a draft`, async ({ page }) => {
    await page.addInitScript(platform => {
      Object.defineProperty(navigator, 'platform', { value: platform })
      localStorage.setItem('transaction-last-account', 'bank')
    }, platform)
    await page.goto('/#/accounts/card/details')
    await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
    await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Card')
    await page.getByLabel('Account', { exact: true }).fill('Bank')
    await page.getByLabel('Account', { exact: true }).press('Enter')
    await page.getByLabel('Description (optional)', { exact: true }).fill('Keep this choice')
    await page.keyboard.press(shortcut)
    await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Bank')
    await expect(page.getByLabel('Description (optional)', { exact: true })).toHaveValue('Keep this choice')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
    await page.keyboard.press(shortcut)
    await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Card')
    await page.keyboard.press('Escape')
    await page.evaluate(() => sessionStorage.setItem('hide-card', '1'))
    await page.keyboard.press(shortcut)
    await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Bank')
  })

  test(`${shortcut} opens from Home and preserves existing drafts`, async ({ page }) => {
    await page.addInitScript(platform => Object.defineProperty(navigator, 'platform', { value: platform }), platform)
    await page.goto('/#/')
    await page.keyboard.press(shortcut)
    const dialog = page.getByRole('dialog', { name: 'Add transaction', exact: true })
    await expect(dialog).toBeVisible()
    await page.getByLabel('Description (optional)', { exact: true }).fill('Keep this draft')
    await page.keyboard.press(shortcut)
    await expect(page.getByLabel('Description (optional)', { exact: true })).toHaveValue('Keep this draft')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Discard changes' }).click()
    await page.keyboard.press(shortcut)
    await expect(dialog).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('link', { name: 'Accounts', exact: true }).click()
    await page.getByRole('button', { name: 'Add account', exact: true }).click()
    await page.getByLabel('Account name', { exact: true }).fill('Unsaved account')
    await page.keyboard.press(shortcut)
    await expect(page.getByRole('dialog', { name: 'Add account', exact: true })).toBeVisible()
    await expect(page.getByLabel('Account name', { exact: true })).toHaveValue('Unsaved account')
  })
}

test('quick entry stays on the current page, remembers successful saves, and accepts no description', async ({ page }) => {
  await page.goto('/#/')
  const add = page.getByRole('button', { name: 'Add transaction', exact: true })
  await add.click()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Transaction type', { exact: true })).toHaveValue('expense')
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Bank')
  await page.getByLabel('Account', { exact: true }).fill('Card'); await page.getByLabel('Account', { exact: true }).press('Enter')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page).toHaveURL(/#\/$/)
  await expect(add).toBeFocused()
  await page.reload()
  await add.click()
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Card')
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeEmpty()
  await page.getByLabel('Account', { exact: true }).fill('Bank'); await page.getByLabel('Account', { exact: true }).press('Enter')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('10')
  await page.evaluate(() => sessionStorage.setItem('fail', '1'))
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Save failed')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Discard changes' }).click()
  await add.click()
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Card')
  await page.keyboard.press('Escape')
  await page.evaluate(() => sessionStorage.setItem('hide-card', '1'))
  await add.click()
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('Bank')
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Transactions', exact: true }).click()
  await expect(page.getByRole('rowheader', { name: 'Expense', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Expense', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Delete “Expense”')
})

test('global entry explains missing prerequisites and retries account loading', async ({ page }) => {
  await page.goto('/#/')
  await page.evaluate(() => sessionStorage.setItem('fail-accounts', '1'))
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Could not load accounts')
  await page.evaluate(() => sessionStorage.removeItem('fail-accounts'))
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await page.evaluate(() => sessionStorage.setItem('no-currency', '1'))
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Choose your currency first')
  await page.keyboard.press('Escape')
  await page.evaluate(() => { sessionStorage.removeItem('no-currency'); sessionStorage.setItem('no-accounts', '1') })
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Add an active account')
})


test('save and add another retains context, clears entry fields, and Enter saves normally', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Transaction type', { exact: true }).selectOption('transfer')
  await page.getByLabel('Date', { exact: true }).fill('2024-02-29')
  await page.getByLabel('From account', { exact: true }).fill('Bank'); await page.getByLabel('From account', { exact: true }).press('Enter')
  await page.getByLabel('To account', { exact: true }).fill('Card'); await page.getByLabel('To account', { exact: true }).press('Enter')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('12.34')
  await page.getByLabel('Description (optional)', { exact: true }).fill('First transfer')
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Add transaction', exact: true })).toBeVisible()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeEmpty()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Description (optional)', { exact: true })).toBeEmpty()
  await expect(page.getByLabel('Transaction type', { exact: true })).toHaveValue('transfer')
  await expect(page.getByLabel('Date', { exact: true })).toHaveValue('2024-02-29')
  await expect(page.getByLabel('From account', { exact: true })).toHaveValue('Bank')
  await expect(page.getByLabel('To account', { exact: true })).toHaveValue('Card')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('5')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const rows = await page.evaluate(() => JSON.parse(localStorage.getItem('transactions') ?? '[]'))
  expect(rows).toHaveLength(2)
  expect(rows[0]).toMatchObject({ amount: '500', description: '', type: 'transfer', date: '2024-02-29', account_id: 'bank', destination_account_id: 'card' })
  expect(rows[1]).toMatchObject({ amount: '1234', description: 'First transfer' })
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(2)
})

test('save and add another preserves failed drafts and blocks dismissal during save', async ({ page }) => {
  await page.goto('/#/')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Amount (THB)', { exact: true }).fill('0')
  await page.getByLabel('Description (optional)', { exact: true }).fill('Keep on failure')
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Amount must be greater than zero')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('20')
  await page.evaluate(() => sessionStorage.setItem('fail', '1'))
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Save failed')
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toHaveValue('20')
  await expect(page.getByLabel('Description (optional)', { exact: true })).toHaveValue('Keep on failure')
  await page.evaluate(() => { sessionStorage.removeItem('fail'); sessionStorage.setItem('hold-save', '1') })
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Saving…', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Save transaction', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new Event('release-save')))
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeEmpty()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('transactions') ?? '[]').length)).toBe(1)
})

test('combined account and type filters show money flow and matching empty states', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.evaluate(() => {
    const rows = ['income', 'expense', 'transfer', 'repayment'].map(type => ({
      id: type, type, description: `Filter ${type}`, amount: '1000', date: '2024-02-29',
      account_id: type === 'expense' ? 'card' : 'bank',
      account_name: type === 'expense' ? 'Card' : 'Bank',
      destination_account_id: ['transfer', 'repayment'].includes(type) ? 'card' : null,
      destination_account_name: ['transfer', 'repayment'].includes(type) ? 'Card' : null,
    }))
    localStorage.setItem('transactions', JSON.stringify(rows))
  })
  await page.reload()
  const history = page.getByRole('table', { name: 'Transaction history' })
  const row = (description: string) => history.locator('tbody').getByRole('row').filter({ has: page.getByRole('rowheader', { name: description, exact: true }) })
  await expect(row('Filter income').getByText('In', { exact: true })).toBeVisible()
  await expect(row('Filter expense').getByText('Out', { exact: true })).toBeVisible()
  await expect(row('Filter transfer').locator('span').filter({ hasText: /^Transfer$/ })).toBeVisible()
  await expect(row('Filter repayment').locator('span').filter({ hasText: /^Transfer$/ })).toBeVisible()
  for (const type of ['income', 'expense', 'transfer', 'repayment']) {
    await page.getByLabel('Filter by transaction type', { exact: true }).selectOption(type)
    await expect(history.locator('tbody').getByRole('row')).toHaveCount(1)
    await expect(row(`Filter ${type}`)).toBeVisible()
  }
  await page.getByLabel('Filter by account').selectOption('bank')
  await expect(row('Filter repayment').getByText('Transfer out', { exact: true })).toBeVisible()
  await page.getByLabel('Filter by account').selectOption('card')
  await expect(row('Filter repayment').getByText('Transfer in', { exact: true })).toBeVisible()
  await page.getByLabel('Filter by transaction type', { exact: true }).selectOption('transfer')
  await expect(row('Filter transfer').getByText('Transfer in', { exact: true })).toBeVisible()
  await page.getByLabel('Filter by transaction type', { exact: true }).selectOption('income')
  await expect(page.getByRole('heading', { name: 'No matching transactions' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'No transactions yet' })).not.toBeVisible()
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await expect(history.locator('tbody').getByRole('row')).toHaveCount(4)
  await expect(page.getByLabel('Filter by transaction type', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Filter by account')).toHaveValue('')
})

test('manage payees and categories, record expenses, and preserve archived history', async ({ page }) => {
  await page.goto('/#/settings')
  for (const [kind, name] of [['payee', 'Corner Shop'], ['category', 'Groceries']]) {
    await page.getByRole('tab', { name: kind === 'payee' ? 'Payees' : 'Categories', exact: true }).click()
    await page.getByRole('button', { name: `Add ${kind}`, exact: true }).click()
    await page.getByLabel(kind === 'payee' ? 'Payee name' : 'Category name', { exact: true }).fill(name)
    if (kind === 'payee') {
      await page.evaluate(() => sessionStorage.setItem('fail-option', '1'))
      await page.getByRole('button', { name: 'Save', exact: true }).click()
      await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Could not save option')
      await page.evaluate(() => sessionStorage.removeItem('fail-option'))
    }
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  await page.reload()
  await page.getByRole('tab', { name: 'Payees', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit Corner Shop' })).toBeVisible()
  await page.getByRole('tab', { name: 'Categories', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit Groceries' })).toBeVisible()
  await page.getByRole('tab', { name: 'Payees', exact: true }).click()
  await page.getByRole('button', { name: 'Add payee', exact: true }).click()
  await page.getByLabel('Payee name', { exact: true }).fill('Corner Shop')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('already exists')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Discard changes' }).click()
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Amount (THB)', { exact: true }).fill('12.50')
  await page.getByLabel('Payee (optional)', { exact: true }).fill('Corner Shop')
  await page.getByRole('option', { name: 'Corner Shop', exact: true }).click()
  await page.getByLabel('Category (optional)', { exact: true }).selectOption({ label: 'Groceries' })
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByLabel('Payee (optional)', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Category (optional)', { exact: true })).toHaveValue('')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('5')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Corner Shop' }).click()
  await page.getByLabel('Payee name', { exact: true }).fill('Local Market')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Archive Local Market' }).click()
  await page.getByRole('tab', { name: 'Categories', exact: true }).click()
  await page.getByRole('button', { name: 'Archive Groceries' }).click()
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByLabel('Payee (optional)').getByRole('option', { name: 'Local Market' })).toHaveCount(0)
  await expect(page.getByLabel('Category (optional)').getByRole('option', { name: 'Groceries' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Transactions', exact: true }).click()
  await expect(page.getByRole('table', { name: 'Transaction history' }).getByRole('row').filter({ has: page.getByRole('cell', { name: 'Local Market', exact: true }) })).toContainText('Groceries')
  await expect(page.getByLabel('Filtered spending')).toContainText('17.50 THB')
  await page.getByLabel('Filter by payee', { exact: true }).selectOption({ label: 'Local Market' })
  await page.getByLabel('Filter by category', { exact: true }).selectOption({ label: 'Groceries' })
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(1)
  await expect(page.getByLabel('Filtered spending')).toContainText('12.50 THB')
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await page.getByLabel('Filter by category').selectOption('unassigned')
  await expect(page.getByLabel('Filtered spending')).toContainText('5.00 THB')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await page.getByRole('tab', { name: 'Payees', exact: true }).click()
  await page.getByRole('button', { name: 'Restore Local Market' }).click()
  await page.getByRole('tab', { name: 'Categories', exact: true }).click()
  await page.getByRole('button', { name: 'Restore Groceries' }).click()
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Payee (optional)', { exact: true }).fill('Local Market')
  await page.getByRole('option', { name: 'Local Market', exact: true }).click()
  await page.getByLabel('Category (optional)').selectOption({ label: 'Groceries' })
  await page.getByLabel('Transaction type', { exact: true }).selectOption('transfer')
  await expect(page.getByLabel('Payee (optional)')).toHaveCount(0)
  await page.getByLabel('To account', { exact: true }).fill('Card'); await page.getByLabel('To account', { exact: true }).press('Enter')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('100')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  const last = await page.evaluate(() => JSON.parse(localStorage.getItem('transactions') ?? '[]')[0])
  expect(last).toMatchObject({ type: 'transfer', payee_id: null, category_id: null })
  await page.getByRole('link', { name: 'Transactions', exact: true }).click()
  await expect(page.getByLabel('Filtered spending')).toContainText('17.50 THB')
})

test('search and create payees inline, preserve drafts on failure, and clear after saving', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.evaluate(() => localStorage.setItem('spending-options', JSON.stringify({ payees: [
    { id: 'shop', name: 'Corner Shop', is_archived: false },
    { id: 'old', name: 'Old Shop', is_archived: true },
  ], categories: [] })))
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  const payee = page.getByRole('combobox', { name: 'Payee (optional)', exact: true })
  await page.getByLabel('Amount (THB)', { exact: true }).fill('12.34')
  await page.getByLabel('Description (optional)', { exact: true }).fill('Lunch')
  await page.getByRole('dialog').evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
  const description = page.getByLabel('Description (optional)', { exact: true })
  const before = await description.boundingBox()
  await payee.click()
  const list = page.getByRole('listbox', { name: 'Payees', exact: true })
  await expect(list).toBeVisible()
  const after = await description.boundingBox()
  expect(after?.y).toBe(before?.y)
  expect(after?.height).toBe(before?.height)
  expect((await list.boundingBox())!.width).toBeCloseTo((await payee.boundingBox())!.width, 0)
  await payee.fill('CORNER   shop')
  await expect(page.getByRole('option', { name: 'Corner Shop', exact: true })).toBeVisible()
  await expect(page.getByRole('option', { name: /Create/ })).toHaveCount(0)
  await payee.press('Enter')
  await expect(payee).toHaveValue('Corner Shop')
  await expect(page.getByRole('dialog')).toBeVisible()
  await payee.fill('Old Shop')
  await expect(page.getByText('This payee is archived.', { exact: false })).toBeVisible()
  await expect(page.getByRole('option', { name: /Create/ })).toHaveCount(0)
  await payee.fill('New   Cafe')
  await payee.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(page.getByText('Discard your unsaved transaction?')).toHaveCount(0)
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Select or create a payee')
  await payee.click()
  await page.evaluate(() => sessionStorage.setItem('fail-option', '1'))
  await page.getByRole('option', { name: 'Create “New Cafe”', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Could not save option' })).toBeVisible()
  await expect(payee).toHaveValue('New   Cafe')
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toHaveValue('12.34')
  await expect(page.getByLabel('Description (optional)', { exact: true })).toHaveValue('Lunch')
  await page.evaluate(() => { sessionStorage.removeItem('fail-option'); sessionStorage.setItem('hold-option', '1') })
  await page.getByRole('option', { name: 'Create “New Cafe”', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save transaction', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new Event('release-option')))
  await expect(payee).toHaveValue('New Cafe')
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(payee).toBeEmpty()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  const saved = await page.evaluate(() => ({ options: JSON.parse(localStorage.getItem('spending-options')!), transactions: JSON.parse(localStorage.getItem('transactions')!) }))
  expect(saved.options.payees).toHaveLength(3)
  expect(saved.transactions).toHaveLength(1)
  expect(saved.transactions[0].payee_id).toBe(saved.options.payees.find((item: { name: string }) => item.name === 'New Cafe').id)
  await payee.fill('New Cafe')
  await expect(page.getByRole('option', { name: 'New Cafe', exact: true })).toBeVisible()
  await page.getByRole('option', { name: 'No payee', exact: true }).click()
  await expect(payee).toBeEmpty()
})


test('income source links salary receipts, preserves failures and clears for another entry', async ({page}) => {
  await page.goto('/#/transactions')
  await page.getByRole('button', {name:'Add transaction',exact:true}).click()
  await page.getByLabel('Transaction type',{exact:true}).selectOption('income')
  await page.getByLabel('Income source (optional)',{exact:true}).selectOption('salary')
  await page.getByLabel('Amount (THB)',{exact:true}).fill('45000')
  await page.screenshot({path:'/tmp/heyday-income-source.png',animations:'disabled'})
  await page.evaluate(()=>sessionStorage.setItem('fail','1'))
  await page.getByRole('button',{name:'Save transaction',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Save failed')
  await expect(page.getByLabel('Income source (optional)',{exact:true})).toHaveValue('salary')
  await page.evaluate(()=>sessionStorage.removeItem('fail'))
  await page.getByRole('button',{name:'Save & add another',exact:true}).click()
  await expect(page.getByLabel('Income source (optional)',{exact:true})).toHaveValue('')
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('transactions')!)[0])).toMatchObject({type:'income',income_source_id:'salary',amount:'4500000',category_id:null})
  await page.getByLabel('Transaction type',{exact:true}).selectOption('expense')
  await expect(page.getByLabel('Income source (optional)',{exact:true})).toHaveCount(0)
})


test('category icons persist across edit, rename and archive with protected drafts',async({page})=>{
 await page.goto('/#/settings')
 await page.getByRole('tab',{name:'Categories',exact:true}).click()
 await page.getByRole('button',{name:'Add category',exact:true}).click()
 await page.getByLabel('Category name',{exact:true}).fill('Dining')
 await page.getByRole('button',{name:'Icon: Food',exact:true}).click()
 await expect(page.getByRole('button',{name:'Icon: Food',exact:true})).toHaveAttribute('aria-pressed','true')
 await page.screenshot({path:'/tmp/heyday-category-icons.png',animations:'disabled'})
 await page.getByRole('button',{name:'Save',exact:true}).click()
 await page.reload()
 await page.getByRole('tab',{name:'Categories',exact:true}).click()
 await page.getByRole('button',{name:'Edit Dining',exact:true}).click()
 await expect(page.getByRole('button',{name:'Icon: Food',exact:true})).toHaveAttribute('aria-pressed','true')
 await page.getByRole('button',{name:'Icon: Drinks',exact:true}).click()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('alert')).toContainText('Discard your unsaved changes')
 await page.getByRole('button',{name:'Keep editing'}).click()
 await page.getByLabel('Category name',{exact:true}).fill('Cafe')
 await page.getByRole('button',{name:'Save',exact:true}).click()
 await page.getByRole('button',{name:'Archive Cafe',exact:true}).click()
 await page.getByRole('button',{name:'Restore Cafe',exact:true}).click()
 await page.getByRole('button',{name:'Edit Cafe',exact:true}).click()
 await expect(page.getByRole('button',{name:'Icon: Drinks',exact:true})).toHaveAttribute('aria-pressed','true')
})

test('account search groups choices, supports keyboards, and restricts destinations', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  const source = page.getByLabel('Account', { exact: true })
  const description = page.getByLabel('Description (optional)', { exact: true })
  await page.getByRole('dialog').evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
  const before = await description.boundingBox()
  await source.click()
  await expect(page.getByRole('listbox', { name: 'Accounts' })).toBeVisible()
  const after = await description.boundingBox()
  expect(after?.y).toBe(before?.y)
  expect(after?.height).toBe(before?.height)
  const inputBounds = await source.boundingBox()
  const listBounds = await page.getByRole('listbox', { name: 'Accounts' }).boundingBox()
  expect(listBounds!.width).toBeCloseTo(inputBounds!.width, 0)
  await expect(page.getByRole('group', { name: 'Bank', exact: true }).getByRole('option', { name: 'Bank', exact: true })).toBeVisible()
  await expect(page.getByRole('group', { name: 'Credit cards', exact: true }).getByRole('option', { name: 'Card', exact: true })).toBeVisible()
  await source.fill('  CREDIT   CARDS ')
  await expect(page.getByRole('listbox').getByRole('option')).toHaveCount(1)
  await source.press('ArrowDown')
  await source.press('Enter')
  await expect(source).toHaveValue('Card')
  await expect(page.getByRole('dialog')).toBeVisible()
  await source.fill('missing')
  await expect(page.getByText('No matching accounts.')).toBeVisible()
  await source.press('Escape')
  await expect(source).toHaveValue('Card')
  await expect(page.getByText('Discard your unsaved transaction?')).toHaveCount(0)
  await source.fill('bank')
  await source.press('Enter')
  await page.getByLabel('Transaction type', { exact: true }).selectOption('repayment')
  const destination = page.getByLabel('To account', { exact: true })
  await destination.click()
  await expect(page.getByRole('listbox').getByRole('option')).toHaveCount(1)
  await expect(page.getByRole('option', { name: 'Card', exact: true })).toBeVisible()
  await destination.fill('BANK')
  await expect(page.getByText('No matching accounts.')).toBeVisible()
  await destination.press('Enter')
  await destination.press('Escape')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('1')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  expect(await page.evaluate(() => localStorage.getItem('transactions'))).toBeNull()
  await destination.fill('cArD')
  await destination.press('Enter')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('transactions')!)[0])).toMatchObject({ account_id: 'bank', destination_account_id: 'card', type: 'repayment' })
})

// Layout errors must be caught even when Vite handles the window error event.
test.afterEach(async ({ page }) => {
  expect(await page.evaluate(() => (window as Window & { uiErrors?: string[] }).uiErrors ?? [])).toEqual([])
})
