import { test, expect } from '@playwright/test'
import type { NewTransaction, Transaction, SaveTransactionOption, TransactionOptions } from '../src/lib/desktop'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, 'isTauri', { value: true })
    Object.defineProperty(window, '__TAURI_INTERNALS__', { value: { invoke: async (command: string, args: { input: NewTransaction & SaveTransactionOption; id: string }) => {
      const rows = (): Transaction[] => JSON.parse(localStorage.getItem('transactions') ?? '[]')
      const accounts = [{ id: 'bank', name: 'Bank', type: 'bank', opening_balance: '10000', current_balance: '10000' }, { id: 'card', name: 'Card', type: 'credit_card', opening_balance: '5000', current_balance: '5000' }].map(account => ({ ...account, institution: null, last_four: null, notes: null, credit_limit: null, statement_day: null, payment_due_day: null, interest_rate_ten_thousandths: null, monthly_installment: null }))
      const options = (): TransactionOptions => JSON.parse(localStorage.getItem('spending-options') ?? '{"payees":[],"categories":[]}')
      const enrichedRows = () => rows().map(row => ({ ...row, payee_name: options().payees.find(item => item.id === row.payee_id)?.name ?? null, category_name: options().categories.find(item => item.id === row.category_id)?.name ?? null }))
      switch (command) {
        case 'plugin:app|version': return '0.1.0'
        case 'get_settings': return { currency: sessionStorage.getItem('no-currency') ? null : 'THB', period_start_day: 1 }
        case 'list_accounts':
          if (sessionStorage.getItem('fail-accounts')) throw 'Load failed'
          return sessionStorage.getItem('no-accounts') ? [] : accounts.filter(a => !sessionStorage.getItem('hide-card') || a.id !== 'card')
        case 'get_financial_data': return { settings: { currency: 'THB', period_start_day: 1 }, accounts, transactions: enrichedRows(), incomes: [], plans: [], categories: options().categories }
        case 'list_transaction_options': return options()
        case 'save_transaction_option': {
          if (sessionStorage.getItem('hold-option')) await new Promise<void>(resolve => window.addEventListener('release-option', () => resolve(), { once: true }))
          if (sessionStorage.getItem('fail-option')) throw 'Could not save option.'
          const lists = options()
          const key = args.input.kind === 'payee' ? 'payees' : 'categories'
          const name = args.input.name.trim().replace(/\s+/g, ' ')
          if (lists[key].some(item => item.id !== args.input.id && item.name.toLowerCase() === name.toLowerCase())) throw 'That name already exists.'
          const value = { id: args.input.id ?? crypto.randomUUID(), name, is_archived: args.input.is_archived }
          lists[key] = [...lists[key].filter(item => item.id !== value.id), value]
          localStorage.setItem('spending-options', JSON.stringify(lists))
          return value
        }
        case 'list_transactions': return enrichedRows()
        case 'create_transaction': {
          if (sessionStorage.getItem('hold-save')) await new Promise<void>(resolve => window.addEventListener('release-save', () => resolve(), { once: true }))
          if (sessionStorage.getItem('fail')) throw 'Save failed. Try again.'
          const row = { ...args.input, id: crypto.randomUUID(), account_name: accounts.find(a => a.id === args.input.account_id)!.name, destination_account_name: args.input.destination_account_id ? 'Card' : null }
          localStorage.setItem('transactions', JSON.stringify([row, ...rows()]))
          return row
        }
        case 'delete_transaction': localStorage.setItem('transactions', JSON.stringify(rows().filter(row => row.id !== args.id))); return
        default: throw new Error(command)
      }
    } } })
  })
})

test('record activity, retain failed forms, filter, and confirm deletion', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Description (optional)', { exact: true }).fill('Unsaved')
  await page.keyboard.press('Escape')
  await expect(page.getByText('Discard your unsaved transaction?')).toBeVisible()
  await page.getByRole('button', { name: 'Discard changes' }).click()
  for (const type of ['expense', 'income', 'transfer', 'repayment']) {
    await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
    await page.getByLabel('Transaction type', { exact: true }).selectOption(type)
    await page.getByLabel(type === 'income' || type === 'expense' ? 'Account' : 'From account', { exact: true }).selectOption('bank')
    if (type === 'transfer' || type === 'repayment') await page.getByLabel('To account', { exact: true }).selectOption('card')
    await page.getByLabel('Amount (THB)', { exact: true }).fill('12.34')
    await page.getByLabel('Description (optional)', { exact: true }).fill(`Test ${type}`)
    if (type === 'expense') {
      await page.evaluate(() => sessionStorage.setItem('fail', '1'))
      await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
      await expect(page.getByRole('alert')).toContainText('Save failed')
      await page.evaluate(() => sessionStorage.removeItem('fail'))
    }
    await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(page.getByRole('rowheader', { name: `Test ${type}` })).toBeVisible()
  }
  await page.reload()
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(4)
  await page.getByLabel('Filter by account').selectOption('card')
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Delete Test repayment', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('rowheader', { name: 'Test repayment' })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Test repayment', exact: true }).click()
  await page.getByRole('button', { name: 'Delete transaction', exact: true }).click()
  await expect(page.getByRole('rowheader', { name: 'Test repayment' })).not.toBeVisible()
})

for (const [platform, shortcut] of [['MacIntel', 'Meta+n'], ['Win32', 'Control+n']]) {
  test(`${shortcut} opens from Home and preserves existing drafts`, async ({ page }) => {
    await page.addInitScript(platform => Object.defineProperty(navigator, 'platform', { value: platform }), platform)
    await page.goto('/#/')
    await page.keyboard.press(shortcut)
    const dialog = page.getByRole('dialog', { name: 'Add transaction', exact: true })
    await expect(dialog).toBeVisible()
    await page.getByLabel('Description (optional)', { exact: true }).fill('Keep this draft')
    await page.keyboard.press(shortcut)
    await expect(page.getByLabel('Description (optional)', { exact: true })).toHaveValue('Keep this draft')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Discard changes' }).click()
    await page.keyboard.press(shortcut)
    await expect(dialog).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('link', { name: 'Accounts', exact: true }).click()
    await page.getByRole('button', { name: 'Add account', exact: true }).click()
    await page.getByLabel('Account name', { exact: true }).fill('Unsaved account')
    await page.keyboard.press(shortcut)
    await expect(page.getByRole('dialog', { name: 'Add account', exact: true })).toBeVisible()
    await expect(page.getByLabel('Account name', { exact: true })).toHaveValue('Unsaved account')
  })
}

test('quick entry stays on the current page, remembers successful saves, and accepts no description', async ({ page }) => {
  await page.goto('/#/')
  const add = page.getByRole('button', { name: 'Add transaction', exact: true })
  await add.click()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Transaction type', { exact: true })).toHaveValue('expense')
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('bank')
  await page.getByLabel('Account', { exact: true }).selectOption('card')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page).toHaveURL(/#\/$/)
  await expect(add).toBeFocused()
  await page.reload()
  await add.click()
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('card')
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeEmpty()
  await page.getByLabel('Account', { exact: true }).selectOption('bank')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('10')
  await page.evaluate(() => sessionStorage.setItem('fail', '1'))
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Save failed')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Discard changes' }).click()
  await add.click()
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('card')
  await page.keyboard.press('Escape')
  await page.evaluate(() => sessionStorage.setItem('hide-card', '1'))
  await add.click()
  await expect(page.getByLabel('Account', { exact: true })).toHaveValue('bank')
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Transactions', exact: true }).click()
  await expect(page.getByRole('rowheader', { name: 'Expense', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Expense', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Delete “Expense”')
})

test('global entry explains missing prerequisites and retries account loading', async ({ page }) => {
  await page.goto('/#/')
  await page.evaluate(() => sessionStorage.setItem('fail-accounts', '1'))
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Could not load accounts')
  await page.evaluate(() => sessionStorage.removeItem('fail-accounts'))
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await page.evaluate(() => sessionStorage.setItem('no-currency', '1'))
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Choose your currency first')
  await page.keyboard.press('Escape')
  await page.evaluate(() => { sessionStorage.removeItem('no-currency'); sessionStorage.setItem('no-accounts', '1') })
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Add an active account')
})


test('save and add another retains context, clears entry fields, and Enter saves normally', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Transaction type', { exact: true }).selectOption('transfer')
  await page.getByLabel('Date', { exact: true }).fill('2024-02-29')
  await page.getByLabel('From account', { exact: true }).selectOption('bank')
  await page.getByLabel('To account', { exact: true }).selectOption('card')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('12.34')
  await page.getByLabel('Description (optional)', { exact: true }).fill('First transfer')
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Add transaction', exact: true })).toBeVisible()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeEmpty()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Description (optional)', { exact: true })).toBeEmpty()
  await expect(page.getByLabel('Transaction type', { exact: true })).toHaveValue('transfer')
  await expect(page.getByLabel('Date', { exact: true })).toHaveValue('2024-02-29')
  await expect(page.getByLabel('From account', { exact: true })).toHaveValue('bank')
  await expect(page.getByLabel('To account', { exact: true })).toHaveValue('card')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('5')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const rows = await page.evaluate(() => JSON.parse(localStorage.getItem('transactions') ?? '[]'))
  expect(rows).toHaveLength(2)
  expect(rows[0]).toMatchObject({ amount: '500', description: '', type: 'transfer', date: '2024-02-29', account_id: 'bank', destination_account_id: 'card' })
  expect(rows[1]).toMatchObject({ amount: '1234', description: 'First transfer' })
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(2)
})

test('save and add another preserves failed drafts and blocks dismissal during save', async ({ page }) => {
  await page.goto('/#/')
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Amount (THB)', { exact: true }).fill('0')
  await page.getByLabel('Description (optional)', { exact: true }).fill('Keep on failure')
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Amount must be greater than zero')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('20')
  await page.evaluate(() => sessionStorage.setItem('fail', '1'))
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Save failed')
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toHaveValue('20')
  await expect(page.getByLabel('Description (optional)', { exact: true })).toHaveValue('Keep on failure')
  await page.evaluate(() => { sessionStorage.removeItem('fail'); sessionStorage.setItem('hold-save', '1') })
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Saving…', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Save transaction', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new Event('release-save')))
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeEmpty()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('transactions') ?? '[]').length)).toBe(1)
})

test('combined account and type filters show money flow and matching empty states', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.evaluate(() => {
    const rows = ['income', 'expense', 'transfer', 'repayment'].map(type => ({
      id: type, type, description: `Filter ${type}`, amount: '1000', date: '2024-02-29',
      account_id: type === 'expense' ? 'card' : 'bank',
      account_name: type === 'expense' ? 'Card' : 'Bank',
      destination_account_id: ['transfer', 'repayment'].includes(type) ? 'card' : null,
      destination_account_name: ['transfer', 'repayment'].includes(type) ? 'Card' : null,
    }))
    localStorage.setItem('transactions', JSON.stringify(rows))
  })
  await page.reload()
  const history = page.getByRole('table', { name: 'Transaction history' })
  const row = (description: string) => history.locator('tbody').getByRole('row').filter({ has: page.getByRole('rowheader', { name: description, exact: true }) })
  await expect(row('Filter income').getByText('In', { exact: true })).toBeVisible()
  await expect(row('Filter expense').getByText('Out', { exact: true })).toBeVisible()
  await expect(row('Filter transfer').locator('span').filter({ hasText: /^Transfer$/ })).toBeVisible()
  await expect(row('Filter repayment').locator('span').filter({ hasText: /^Transfer$/ })).toBeVisible()
  for (const type of ['income', 'expense', 'transfer', 'repayment']) {
    await page.getByLabel('Filter by transaction type', { exact: true }).selectOption(type)
    await expect(history.locator('tbody').getByRole('row')).toHaveCount(1)
    await expect(row(`Filter ${type}`)).toBeVisible()
  }
  await page.getByLabel('Filter by account').selectOption('bank')
  await expect(row('Filter repayment').getByText('Transfer out', { exact: true })).toBeVisible()
  await page.getByLabel('Filter by account').selectOption('card')
  await expect(row('Filter repayment').getByText('Transfer in', { exact: true })).toBeVisible()
  await page.getByLabel('Filter by transaction type', { exact: true }).selectOption('transfer')
  await expect(row('Filter transfer').getByText('Transfer in', { exact: true })).toBeVisible()
  await page.getByLabel('Filter by transaction type', { exact: true }).selectOption('income')
  await expect(page.getByRole('heading', { name: 'No matching transactions' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'No transactions yet' })).not.toBeVisible()
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await expect(history.locator('tbody').getByRole('row')).toHaveCount(4)
  await expect(page.getByLabel('Filter by transaction type', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Filter by account')).toHaveValue('')
})

test('manage payees and categories, record expenses, and preserve archived history', async ({ page }) => {
  await page.goto('/#/settings')
  for (const [kind, name] of [['payee', 'Corner Shop'], ['category', 'Groceries']]) {
    await page.getByRole('tab', { name: kind === 'payee' ? 'Payees' : 'Categories', exact: true }).click()
    await page.getByRole('button', { name: `Add ${kind}`, exact: true }).click()
    await page.getByLabel(kind === 'payee' ? 'Payee name' : 'Category name', { exact: true }).fill(name)
    if (kind === 'payee') {
      await page.evaluate(() => sessionStorage.setItem('fail-option', '1'))
      await page.getByRole('button', { name: 'Save', exact: true }).click()
      await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Could not save option')
      await page.evaluate(() => sessionStorage.removeItem('fail-option'))
    }
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  await page.reload()
  await page.getByRole('tab', { name: 'Payees', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Rename Corner Shop' })).toBeVisible()
  await page.getByRole('tab', { name: 'Categories', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Rename Groceries' })).toBeVisible()
  await page.getByRole('tab', { name: 'Payees', exact: true }).click()
  await page.getByRole('button', { name: 'Add payee', exact: true }).click()
  await page.getByLabel('Payee name', { exact: true }).fill('Corner Shop')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('already exists')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Discard changes' }).click()
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Amount (THB)', { exact: true }).fill('12.50')
  await page.getByLabel('Payee (optional)', { exact: true }).fill('Corner Shop')
  await page.getByRole('option', { name: 'Corner Shop', exact: true }).click()
  await page.getByLabel('Category (optional)', { exact: true }).selectOption({ label: 'Groceries' })
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(page.getByLabel('Payee (optional)', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Category (optional)', { exact: true })).toHaveValue('')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('5')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await page.getByRole('button', { name: 'Rename Corner Shop' }).click()
  await page.getByLabel('Payee name', { exact: true }).fill('Local Market')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Archive Local Market' }).click()
  await page.getByRole('tab', { name: 'Categories', exact: true }).click()
  await page.getByRole('button', { name: 'Archive Groceries' }).click()
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await expect(page.getByLabel('Payee (optional)').getByRole('option', { name: 'Local Market' })).toHaveCount(0)
  await expect(page.getByLabel('Category (optional)').getByRole('option', { name: 'Groceries' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: 'Transactions', exact: true }).click()
  await expect(page.getByRole('table', { name: 'Transaction history' }).getByRole('row').filter({ has: page.getByRole('cell', { name: 'Local Market', exact: true }) })).toContainText('Groceries')
  await expect(page.getByLabel('Filtered spending')).toContainText('17.50 THB')
  await page.getByLabel('Filter by payee', { exact: true }).selectOption({ label: 'Local Market' })
  await page.getByLabel('Filter by category', { exact: true }).selectOption({ label: 'Groceries' })
  await expect(page.getByRole('table', { name: 'Transaction history' }).locator('tbody').getByRole('row')).toHaveCount(1)
  await expect(page.getByLabel('Filtered spending')).toContainText('12.50 THB')
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await page.getByLabel('Filter by category').selectOption('unassigned')
  await expect(page.getByLabel('Filtered spending')).toContainText('5.00 THB')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await page.getByRole('tab', { name: 'Payees', exact: true }).click()
  await page.getByRole('button', { name: 'Restore Local Market' }).click()
  await page.getByRole('tab', { name: 'Categories', exact: true }).click()
  await page.getByRole('button', { name: 'Restore Groceries' }).click()
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  await page.getByLabel('Payee (optional)', { exact: true }).fill('Local Market')
  await page.getByRole('option', { name: 'Local Market', exact: true }).click()
  await page.getByLabel('Category (optional)').selectOption({ label: 'Groceries' })
  await page.getByLabel('Transaction type', { exact: true }).selectOption('transfer')
  await expect(page.getByLabel('Payee (optional)')).toHaveCount(0)
  await page.getByLabel('To account', { exact: true }).selectOption('card')
  await page.getByLabel('Amount (THB)', { exact: true }).fill('100')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  const last = await page.evaluate(() => JSON.parse(localStorage.getItem('transactions') ?? '[]')[0])
  expect(last).toMatchObject({ type: 'transfer', payee_id: null, category_id: null })
  await page.getByRole('link', { name: 'Transactions', exact: true }).click()
  await expect(page.getByLabel('Filtered spending')).toContainText('17.50 THB')
})

test('search and create payees inline, preserve drafts on failure, and clear after saving', async ({ page }) => {
  await page.goto('/#/transactions')
  await page.evaluate(() => localStorage.setItem('spending-options', JSON.stringify({ payees: [
    { id: 'shop', name: 'Corner Shop', is_archived: false },
    { id: 'old', name: 'Old Shop', is_archived: true },
  ], categories: [] })))
  await page.getByRole('button', { name: 'Add transaction', exact: true }).click()
  const payee = page.getByRole('combobox', { name: 'Payee (optional)', exact: true })
  await page.getByLabel('Amount (THB)', { exact: true }).fill('12.34')
  await page.getByLabel('Description (optional)', { exact: true }).fill('Lunch')
  await payee.fill('CORNER   shop')
  await expect(page.getByRole('option', { name: 'Corner Shop', exact: true })).toBeVisible()
  await expect(page.getByRole('option', { name: /Create/ })).toHaveCount(0)
  await payee.press('Enter')
  await expect(payee).toHaveValue('Corner Shop')
  await expect(page.getByRole('dialog')).toBeVisible()
  await payee.fill('Old Shop')
  await expect(page.getByText('This payee is archived.', { exact: false })).toBeVisible()
  await expect(page.getByRole('option', { name: /Create/ })).toHaveCount(0)
  await payee.fill('New   Cafe')
  await payee.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(page.getByText('Discard your unsaved transaction?')).toHaveCount(0)
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Select or create a payee')
  await payee.click()
  await page.evaluate(() => sessionStorage.setItem('fail-option', '1'))
  await page.getByRole('option', { name: 'Create “New Cafe”', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Could not save option' })).toBeVisible()
  await expect(payee).toHaveValue('New   Cafe')
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toHaveValue('12.34')
  await expect(page.getByLabel('Description (optional)', { exact: true })).toHaveValue('Lunch')
  await page.evaluate(() => { sessionStorage.removeItem('fail-option'); sessionStorage.setItem('hold-option', '1') })
  await page.getByRole('option', { name: 'Create “New Cafe”', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save transaction', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new Event('release-option')))
  await expect(payee).toHaveValue('New Cafe')
  await page.getByRole('button', { name: 'Save & add another', exact: true }).click()
  await expect(payee).toBeEmpty()
  await expect(page.getByLabel('Amount (THB)', { exact: true })).toBeFocused()
  const saved = await page.evaluate(() => ({ options: JSON.parse(localStorage.getItem('spending-options')!), transactions: JSON.parse(localStorage.getItem('transactions')!) }))
  expect(saved.options.payees).toHaveLength(3)
  expect(saved.transactions).toHaveLength(1)
  expect(saved.transactions[0].payee_id).toBe(saved.options.payees.find((item: { name: string }) => item.name === 'New Cafe').id)
  await payee.fill('New Cafe')
  await expect(page.getByRole('option', { name: 'New Cafe', exact: true })).toBeVisible()
  await page.getByRole('option', { name: 'No payee', exact: true }).click()
  await expect(payee).toBeEmpty()
})
