import { t as translate, useLanguage } from "../lib/i18n"
import { AccountLabel } from './InstitutionLogo'
import { useCardLimits } from '../lib/card-limits'
import { CardCredit } from './SharedCreditLimits'
import { AccountSelect } from './AccountSelect'
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { Link, useParams } from '@tanstack/react-router'
import { toast } from 'sonner'
import { desktopAvailable, listAccounts, type Account } from '../lib/desktop'
import { getCardBilling, saveCardStatement, saveCardPaymentPlan, recordCardPayment, removeCardBillingRecord, statementTotals, statementLedger, spendingCategories, draftBillingDates, localToday, type AccountBilling, type CardStatement } from '../lib/card-billing'
import { installmentSchedule } from '../lib/installments'
import { formatAmount, fractionDigits, decimalToInteger } from '../lib/money'
import { useLocalDate } from '../lib/useLocalDate'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { NativeSelect } from './ui/native-select'
import { FormField as Field } from './FormField'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from './ui/dialog'
const message=(e:unknown)=>e instanceof Error?e.message:String(e)
const decimal=(v:string,c:string)=>{const n=BigInt(v),d=fractionDigits(c),scale=10n**BigInt(d);return `${n/scale}${d?'.'+(n%scale).toString().padStart(d,'0'):''}`}
type Editor={kind:'statement';statement?:CardStatement}|{kind:'plan'|'payment'|'link';statement:CardStatement}|{kind:'remove';record:'statement'|'plan'|'allocation';id:string}
export function CardBillingPage(){
  useLanguage()
const {accountId}=useParams({from:'/accounts/$accountId/billing'});return <CardBilling key={accountId} accountId={accountId}/>}
function CardBilling({accountId}:{accountId:string}){
  useLanguage()

 const limits=useCardLimits()
 const [data,setData]=useState<AccountBilling|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[error,setError]=useState<string|null>(null),[editor,setEditor]=useState<Editor|null>(null)
 useLocalDate()
 const request=useRef(0)
 const refresh=useCallback(async()=>{const id=++request.current;try{const [result,accounts]=await Promise.all([getCardBilling(accountId),listAccounts()]);if(request.current===id){setData(result);setAccounts(accounts);setError(null)}}catch(e){if(request.current===id)setError(message(e))}},[accountId])
 useEffect(()=>{if(!desktopAvailable)return;void refresh();const listener=()=>{void refresh()};const events=['accounts-changed','transactions-changed','plans-changed','focus'];events.forEach(e=>window.addEventListener(e,listener));return()=>{request.current++;events.forEach(e=>window.removeEventListener(e,listener))}},[refresh])
 if(!desktopAvailable)return <p>{translate("Open the desktop app to manage card billing.")}</p>
 if(!data)return <p role={error?'alert':'status'}>{error??translate("Loading card billing…")}</p>
 const currency=data.currency!,money=(n:string|bigint)=>formatAmount(n.toString(),currency),debt=BigInt(data.account.current_balance),active=accounts.some(a=>a.id===accountId)
 const unbilled=data.transactions.filter(t=>t.type==='expense'&&t.account_id===accountId&&!data.entries.some(e=>e.transaction_id===t.id))
 return <section className="space-y-5"><Link to="/accounts" className="text-brand">{translate("← Accounts")}</Link><h2 className="text-2xl font-semibold"><AccountLabel id={data.account.id} name={data.account.name} /> {" "}{translate("· Billing")}</h2>
 <nav aria-label={translate("Card account views")} className="flex gap-3 border-b border-line pb-3"><Link to="/accounts/$accountId" params={{accountId}} className="text-brand">{translate("Transactions & reconciliation")}</Link><span aria-current="page" className="font-semibold">{translate("Billing")}</span></nav>
 {error&&<p role="alert">{translate(error)}</p>}
 <CardCredit id={accountId} individualLimit={data.account.credit_limit} balance={data.account.current_balance} currency={data.currency!} limits={limits} />
 <div className="grid gap-3 sm:grid-cols-3">{[[translate('Current amount owed / credit'),money(debt)],[translate("Unbilled recorded purchases"),money(unbilled.reduce((n,t)=>n+BigInt(t.amount),0n))]].map(([label,value])=><div key={label} className="rounded-2xl border border-line bg-card p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div>
 <p className="text-sm">{translate("Purchases are category expenses and increase card debt. Payments reduce cash and debt; they are not another category expense. Negative debt is a credit. Statement confirmation never changes account balances.")}</p>
 <details className="rounded-xl border border-line p-4"><summary className="cursor-pointer">{translate("Unbilled purchases (")}{unbilled.length})</summary>{unbilled.map(t=><p key={t.id} className="mt-2 flex justify-between gap-4 text-sm"><span>{t.date} · {t.description||translate("Expense")} · {t.category_name??translate("Uncategorized")}</span><span>{money(t.amount)}</span></p>)}</details>
 <Button disabled={!active} onClick={()=>setEditor({kind:'statement'})}>{translate("Review new statement")}</Button>
 {!data.billing.statements.length&&<p>{translate("No confirmed statements. Review your issuer’s statement to enter the amount, minimum due and due date.")}</p>}
 {data.billing.statements.map(s=>{const t=statementTotals(data.billing,s),ledger=statementLedger(data.account,data.transactions,s.start_date,s.end_date),categories=spendingCategories(data.transactions,accountId,s.start_date,s.end_date+'~');return <article key={s.id} className="space-y-4 rounded-2xl border border-line bg-card p-5">
 <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-semibold">{s.start_date} – {s.end_date}</h3><p className="text-sm">{translate("Due")}{" "}{s.due_date} · {translate(t.status)}</p></div><Button variant="outline" disabled={!active} onClick={()=>setEditor({kind:'statement',statement:s})}>{translate("Review statement")}</Button></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[translate("Statement amount"),BigInt(s.amount)],[translate("Applied payments"),t.paid],[translate("Statement remaining"),t.remaining],[translate("Minimum remaining"),t.minimum]].map(([label,n])=><div key={String(label)}><p className="text-xs text-muted">{String(label)}</p><p className="font-semibold tabular-nums">{money(n as bigint)}</p></div>)}</div>
 <details><summary className="cursor-pointer font-medium">{translate("Bill summary and spending by category")}</summary><div className="mt-3 grid gap-5 md:grid-cols-2"><div className="space-y-2"><h4 className="font-semibold">{translate("Recorded ledger activity")}</h4>{[[translate("Previous recorded balance"),ledger.previous],[translate("Purchases"),ledger.purchases],[translate("Payments during billing period"),-ledger.payments],[translate('Other changes / credits'),ledger.adjustments],[translate("Recorded closing balance"),ledger.total]].map(([label,n])=><p key={String(label)} className="flex justify-between gap-3 text-sm"><span>{String(label)}</span><span>{money(n as bigint)}</span></p>)}<p className="text-xs">{translate("Difference from issuer statement:")}{" "}{money(BigInt(s.amount)-ledger.total)}{translate(". These figures are current recorded evidence; missing entries or installment billing can differ. Review transactions; no automatic adjustment is made.")}</p></div><div><h4 className="font-semibold">{translate("Spending by category")}</h4><p className="mb-2 text-xs">{translate("Purchases — excluded from cash outflow totals.")}</p>{categories.map(c=><details key={c.name} className="py-2"><summary className="cursor-pointer">{c.name} · {money(c.amount)}</summary>{c.transactions.map(t=><p key={t.id} className="mt-1 text-sm">{t.date} · {t.description||translate("Expense")} · {money(t.amount)}</p>)}</details>)}{!categories.length&&<p className="text-sm">{translate("No recorded purchases in this period. Previous debt has no inferred category.")}</p>}</div></div></details>
 <div className="rounded-xl bg-soft p-4 text-sm">{t.plan?<><p>{translate("Plan:")}{" "}{t.plan.mode==='full'?translate("Full statement balance"):t.plan.mode==='minimum'?translate("Minimum payment"):translate("Custom / partial payment")} · {t.plan.date} · {accounts.find(a=>a.id===t.plan!.account_id)?.name??translate("Unavailable account")}</p><p>{translate("Recorded")}{" "}{money(t.paid)} {" "}{translate("+ still planned")}{" "}{money(t.planned)} {" "}{translate("· Remaining after plan")}{" "}{money(t.afterPlan)}</p><p>{!t.plan.available?translate("Account unavailable · excluded from forecast"):s.needs_review?translate("Statement needs review · planned amount excluded from forecast"):t.plan.date<localToday()&&t.planned>0n?translate("Needs review · past planned date; not moved forward"):translate("Forecast uses remaining plan only.")} {t.planned<t.minimum?translate("Plan does not cover remaining minimum."):''} {t.plan.date>s.due_date?translate("Planned after due date."):''}</p></>:<p>{translate("Not planned · Statement debt is not treated as a cash payment.")}</p>}<p className="mt-1 text-xs">{translate("Remaining debt excludes future interest, fees and new purchases.")}</p></div>
 <div className="flex flex-wrap gap-2"><Button disabled={!active||t.remaining===0n} onClick={()=>setEditor({kind:'plan',statement:s})}>{t.plan?translate("Edit payment plan"):translate("Plan payment")}</Button><Button variant="outline" disabled={!active||t.remaining===0n} onClick={()=>setEditor({kind:'payment',statement:s})}>{translate("Record payment")}</Button><Button variant="outline" disabled={t.remaining===0n} onClick={()=>setEditor({kind:'link',statement:s})}>{translate("Link existing payment")}</Button>{t.plan&&<Button variant="ghost" onClick={()=>setEditor({kind:'remove',record:'plan',id:s.id})}>{translate("Remove plan")}</Button>}<Button variant="ghost" onClick={()=>setEditor({kind:'remove',record:'statement',id:s.id})}>{translate("Remove statement")}</Button></div>
 {data.billing.allocations.filter(a=>a.statement_id===s.id).map(a=><p key={a.transaction_id} className="flex flex-wrap items-center gap-3 text-sm">{a.date} {" "}{translate("· Applied")}{" "}{money(a.amount)}<Button size="xs" variant="ghost" onClick={()=>setEditor({kind:'remove',record:'allocation',id:a.transaction_id})}>{translate("Unlink payment")}</Button></p>)}
 </article>})}
 <p className="text-xs">{translate("Payment allocation is explicit. One payment links to one statement; record separate transactions when splitting across bills. Removing a statement or unlinking a payment preserves actual transactions. Review carried balances across statements to avoid planning the same old debt twice.")}</p>
 {editor&&<BillingEditor editor={editor} data={data} accounts={accounts} close={()=>setEditor(null)} saved={()=>{setEditor(null);void refresh()}}/>}
 </section>
}
function BillingEditor({editor,data,accounts,close,saved}:{editor:Editor;data:AccountBilling;accounts:Account[];close:()=>void;saved:()=>void}){
  useLanguage()

 const statement='statement'in editor?editor.statement:undefined,currency=data.currency!,money=(n:string|bigint)=>formatAmount(n.toString(),currency)
 const plan=data.billing.plans.find(p=>p.statement_id===statement?.id)
 const [dates,setDates]=useState(statement?{start_date:statement.start_date,end_date:statement.end_date,due_date:statement.due_date}:draftBillingDates(data.account.statement_day,data.account.payment_due_day))
 const [mode,setMode]=useState(plan?.mode??'full'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false)
 const [coverage,setCoverage]=useState(data.billing.installments.filter(c=>c.statement_id===statement?.id).map(c=>({installment_id:c.installment_id,date:c.date})))
 const lock=useRef(false),requestClose=()=>{if(lock.current)return;if(dirty)setDiscard(true);else close()}
 const cash=accounts.filter(a=>['cash','bank','wallet'].includes(a.type)),ledger=statementLedger(data.account,data.transactions,dates.start_date,dates.end_date)
 const candidates=data.installments.flatMap(i=>installmentSchedule(i).map(p=>({...p,id:i.id,name:i.name})))
 const eligible=data.transactions.filter(t=>['repayment','transfer'].includes(t.type)&&t.destination_account_id===data.account.id&&t.date>(statement?.end_date??'')&&!data.billing.allocations.some(a=>a.transaction_id===t.id))
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current||discard)return;lock.current=true;setBusy(true);setError(null);const form=new FormData(e.currentTarget),text=(n:string)=>String(form.get(n)??''),minor=(n:string)=>decimalToInteger(text(n),fractionDigits(currency))
 try{
 if(editor.kind==='statement')await saveCardStatement({id:statement?.id??null,account_id:data.account.id,...dates,amount:minor('amount'),minimum:minor('minimum'),currency,installments:coverage})
 if(editor.kind==='plan')await saveCardPaymentPlan({statement_id:editor.statement.id,account_id:text('account'),date:text('date'),mode,target:mode==='custom'?minor('target'):'0',currency})
 if(editor.kind==='payment'||editor.kind==='link')await recordCardPayment({statement_id:editor.statement.id,transaction_id:editor.kind==='link'?text('transaction'):null,account_id:text('account'),date:text('date'),amount:editor.kind==='payment'?minor('amount'):'0',currency})
 if(editor.kind==='remove')await removeCardBillingRecord(editor.record,editor.id)
 toast.success(editor.kind==='payment'?translate("Payment recorded. Balances updated."):editor.kind==='remove'?translate("Billing record removed. Transactions preserved."):translate("Billing saved."));saved()
 }catch(e){setError(message(e))}finally{lock.current=false;setBusy(false)}}
 const field=(label:string,name:string,value?:string,props:Record<string,unknown>={})=><Field label={label}><Input name={name} defaultValue={value} required {...props}/></Field>
 const accountField=<Field label={translate("Pay from")}><AccountSelect name="account" required defaultValue={plan?.account_id??''}><option value="">{translate("Choose account")}</option>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</AccountSelect></Field>
 return <Dialog open onOpenChange={open=>{if(!open)requestClose()}}><DialogContent className="flex max-h-[85dvh] flex-col overflow-hidden p-0 sm:max-w-[650px]" showCloseButton={!busy} onInteractOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{if(busy)e.preventDefault()}}><DialogHeader className="px-6 pt-6"><DialogTitle>{editor.kind==='statement'?translate("Review statement"):editor.kind==='plan'?translate("Plan payment"):editor.kind==='payment'?translate("Record payment"):editor.kind==='link'?translate("Link existing payment"):translate("Remove billing record?")}</DialogTitle><DialogDescription><AccountLabel id={data.account.id} name={data.account.name} /> · {currency}</DialogDescription></DialogHeader>
 <form onSubmit={submit} onChange={()=>setDirty(true)} className="flex min-h-0 flex-col"><div className="min-h-0 overflow-y-auto"><fieldset disabled={busy} className="space-y-4 p-6">
 {editor.kind==='statement'&&<><p className="text-sm">{translate("Confirm the issuer’s exact dates, balance and minimum. Dates below are suggestions from account settings. No balance adjustment or interest calculation occurs.")}</p>{(['start_date','end_date','due_date'] as const).map((key,i)=><Field key={key} label={[translate("Billing start"),translate("Billing end (inclusive)"),translate("Payment due date")][i]}><Input type="date" required value={dates[key]} max={key==='end_date'?localToday():undefined} onChange={e=>setDates(v=>({...v,[key]:e.target.value}))}/></Field>)}<p className="text-sm">{translate("Recorded closing balance:")}{" "}{money(ledger.total)}{translate(". Use your issuer’s amount below, even if it differs.")}</p>{field(translate("Statement amount"),'amount',statement?decimal(statement.amount,currency):undefined,{inputMode:'decimal'})}{field(translate("Minimum due (from issuer)"),'minimum',statement?decimal(statement.minimum,currency):undefined,{inputMode:'decimal'})}<div className="space-y-2"><p className="font-medium">{translate("Installments included in this bill")}</p>{coverage.length>0&&<Button type="button" variant="outline" size="xs" onClick={()=>{setCoverage([]);setDirty(true)}}>{translate("Clear installment inclusions")}</Button>}<p className="text-xs">{translate("Select the exact scheduled occurrence shown on your issuer’s bill. The billing range and payment due month do not determine the installment occurrence. Only that occurrence’s separate Outlook estimate is suppressed; the bill payment uses its planned payment date. This does not mark an installment paid. Saved cycle overrides are preserved.")}</p><div className="max-h-64 space-y-2 overflow-y-auto rounded-lg border border-line p-3">{candidates.map(p=>{const checked=coverage.some(c=>c.installment_id===p.id&&c.date===p.date),other=data.billing.installments.some(c=>c.installment_id===p.id&&c.date===p.date&&c.statement_id!==statement?.id);return <label key={p.id+p.date} className="flex items-center gap-2 text-sm"><Input type="checkbox" className="size-4" checked={checked} disabled={other} onChange={e=>setCoverage(v=>e.target.checked?[...v,{installment_id:p.id,date:p.date}]:v.filter(c=>c.installment_id!==p.id||c.date!==p.date))}/>{p.name} · {p.date} · {money(p.amount)}{other?translate(" · Already included"):''}</label>})}{!candidates.length&&<p className="text-sm">{translate("No saved installment occurrences.")}</p>}</div>{coverage.filter(c=>!candidates.some(p=>p.id===c.installment_id&&p.date===c.date)).map(c=><label key={c.installment_id+c.date} className="flex items-center gap-2 text-sm"><Input type="checkbox" className="size-4" checked onChange={()=>setCoverage(v=>v.filter(x=>x!==c))}/>{c.date} {" "}{translate("· No longer in the schedule — remove this inclusion before confirming.")}</label>)}</div></>}
 {editor.kind==='plan'&&<><Field label={translate("Payment option")}><NativeSelect value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="full">{translate("Full statement balance")}</option><option value="minimum">{translate("Minimum payment")}</option><option value="custom">{translate("Custom / partial payment")}</option></NativeSelect></Field>{mode==='custom'?field(translate("Total payment target (including already applied payments)"),'target',plan?decimal(plan.target,currency):undefined,{inputMode:'decimal'}):<p>{translate("Total target:")}{" "}{money(mode==='full'?editor.statement.amount:editor.statement.minimum)}</p>}<p className="text-xs">{translate("Applied payments reduce this target. The remaining amount is scheduled below. This plan does not record a payment.")}</p>{accountField}{field(translate("Planned payment date"),'date',plan?.date??(editor.statement.due_date>localToday()?editor.statement.due_date:localToday()),{type:'date',min:localToday()})}</>}
 {editor.kind==='payment'&&<>{accountField}{field(translate("Payment amount"),'amount',undefined,{inputMode:'decimal'})}{field(translate("Payment date"),'date',localToday(),{type:'date',max:localToday()})}<p className="text-sm">{translate("Records a repayment, reduces cash and card debt, and applies it to this statement atomically. If already recorded, cancel and use Link existing payment.")}</p></>}
 {editor.kind==='link'&&<><Field label={translate("Existing payment")}><AccountSelect accountIds={Object.fromEntries(eligible.map(t => [t.id, t.account_id]))} name="transaction" required><option value="">{translate("Choose recorded payment")}</option>{eligible.map(t=><option key={t.id} value={t.id}>{t.date} · {t.account_name} · {money(t.amount)}</option>)}</AccountSelect></Field><p className="text-sm">{translate("Only cash, bank or wallet payments to this card after statement close can be linked. Linking does not change balances.")}</p></>}
 {editor.kind==='remove'&&<p>{translate("This removes the")}{" "}{editor.record==='allocation'?translate("payment link"):editor.record}{translate(". Recorded transactions and balances remain. Removing a statement also removes its payment plan and restores separate installment estimates.")}</p>}
 {error&&<p role="alert">{translate(error)}</p>}</fieldset></div><DialogFooter className="shrink-0 border-t border-line p-4">{discard?<><p>{translate("Discard unsaved changes?")}</p><Button type="button" variant="outline" onClick={()=>setDiscard(false)}>{translate("Keep editing")}</Button><Button type="button" variant="destructive" onClick={close}>{translate("Discard")}</Button></>:<><Button type="button" variant="outline" disabled={busy} onClick={requestClose}>{translate("Cancel")}</Button><Button type="submit" disabled={busy}>{busy?translate("Saving…"):editor.kind==='remove'?translate("Remove"):editor.kind==='statement'?translate("Confirm statement"):translate("Save")}</Button></>}</DialogFooter></form></DialogContent></Dialog>
}
