import { Link } from '@tanstack/react-router'
import { statementTotals, spendingCategories } from '../lib/card-billing'
import { boundary, addMonths, plannerMoney, type PlannerData } from '../lib/cashflow'
import { dateKey } from '../lib/financial'
export function CardOutlookDetails({data,months}:{data:PlannerData;months:string[]}){
 if(data.source_currency!=='THB')return null
 const billing=data.card_billing
 return <details className="mb-4 rounded-xl border border-line bg-card p-4"><summary className="cursor-pointer font-semibold">Credit card bills & spending details</summary><p className="my-3 text-sm">Bill plans affect cash on the planned payment date. Purchases below are category spending only — excluded from cash outflow totals. Review manual plans for duplicates.</p>
 {data.credit_cards.map(card=><details key={card.id} className="border-t border-line py-3"><summary className="cursor-pointer font-medium">{card.name}</summary><Link to="/accounts/$accountId/billing" params={{accountId:card.id}} className="my-2 inline-block text-sm text-brand">Manage billing & payments</Link>
 {billing?.statements.filter(s=>s.account_id===card.id).map(s=>{const t=statementTotals(billing,s);return <div key={s.id} className="mb-3 rounded-lg bg-soft p-3 text-sm"><p className="font-medium">Bill ending {s.end_date} · Due {s.due_date} · {t.status}</p><p>Statement remaining {plannerMoney(t.remaining)} · Minimum remaining {plannerMoney(t.minimum)}</p><p>Applied payments {plannerMoney(t.paid)} · {t.plan?`${t.plan.mode==='full'?'Full statement':t.plan.mode==='minimum'?'Minimum':'Partial'} plan on ${t.plan.date}: ${plannerMoney(t.planned)} remaining`:'Not planned'}</p>{t.plan&&<p>After plan: {plannerMoney(t.afterPlan)} remaining, excluding future interest and fees. {t.planned<t.minimum?'Plan is below the remaining minimum.':''} {t.plan.date>s.due_date?'Planned after due date.':''} {t.forecast===0n&&t.planned>0n?'Needs review / unavailable: excluded from forecast.':''}</p>}</div>})}
 {!billing?.statements.some(s=>s.account_id===card.id)&&<p className="mb-2 text-sm">No confirmed bills. Existing recorded-payment and installment estimates apply.</p>}
 <details><summary className="cursor-pointer text-sm font-medium">Spending by category · purchases, not cash payments</summary>{months.map(month=>{const start=dateKey(boundary(month,data.period_start_day)),end=dateKey(boundary(addMonths(month,1),data.period_start_day)),categories=spendingCategories(data.card_transactions,card.id,start,end);return <div key={month} className="mt-3 text-sm"><h4 className="font-medium">{month} · {start} to {end} (exclusive)</h4>{categories.map(c=><details key={c.name} className="pl-3"><summary className="cursor-pointer">{c.name}: {plannerMoney(c.amount)}</summary>{c.transactions.map(t=><p key={t.id} className="pl-3 text-xs">{t.date} · {plannerMoney(BigInt(t.amount))}</p>)}</details>)}{!categories.length&&<p className="text-xs text-muted">No recorded purchases.</p>}</div>})}</details>
 </details>)}
 </details>
}
